name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get update && sudo apt-get install -y potrace libagg-dev libpotrace-dev build-essential pkg-config
      - run: pip install -r requirements.txt ruff black pytest
      - run: ruff check --fix .
      - run: black --check .
      - run: pytest --maxfail=1 --disable-warnings
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/vectorize-svc:${{ github.sha }} .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/vectorize-svc:${{ github.sha }}
