name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get update && sudo apt-get install -y potrace libagg-dev libpotrace-dev
      - run: pip install -r requirements.txt ruff black pytest
      - run: ruff --fix .
      - run: black --check .
      - run: pytest --maxfail=1 --disable-warnings
      - run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/${{ github.repository }}/vectorize-svc:${{ github.sha }} .
      - run: docker push ghcr.io/${{ github.repository }}/vectorize-svc:${{ github.sha }}
